### ISSUE TITLE
Background image in css file not showing up

### ISSUE THREAD

**Issue by tinar9678** [tinar9678/tinar9678.github.io#1]
Hi,

So I'm trying to display an image on my site, but it is not showing up. However, when I just double click on the html file to display the webpage, the picture shows up fine.

I don't understand what the problem is because I have the image file stored inside a folder on the same repository. Not sure if this is a bug or if I'm just missing something.
My website repo: 
https://github.com/tinar9678/tinar9678.github.io

**Comment by sthodup1** [comment]
Where on your site are you trying to display the image?

**Comment by tinar9678** [comment]
@sthodup1 I'm trying to display it as a fullscreen -- the content is below the image!

**Comment by sthodup1** [comment]
What did you try that didn't work?

**Comment by tinar9678** [comment]
<img width="823" alt="screen shot 2016-06-22 at 6 59 30 pm" src="https://cloud.githubusercontent.com/assets/16639660/16289615/8295af4e-38ab-11e6-8cbf-2b9772c71914.png">

background: url() isn't displaying the image. 

https://github.com/tinar9678/tinar9678.github.io to check out my code and pictures 

@sthodup1

**Comment by sthodup1** [comment]
I don't think you can use that link for the picture url. That link opens up the github page with the editor. Try [https://raw.githubusercontent.com/tinar9678/tinar9678.github.io/master/pictures/welcome.jpg](https://raw.githubusercontent.com/tinar9678/tinar9678.github.io/master/pictures/welcome.jpg) instead

**Comment by tinar9678** [comment]
@sthodup1 Works perfectly. Thank you so much for you help!!!

**Comment by tinar9678** [comment]
@sthodup1 Where did you get the link to the image? I want to remember for future reference!! thanks so much again!!

**Comment by sthodup1** [comment]
@tinar9678 On [https://github.com/tinar9678/tinar9678.github.io/blob/master/pictures/profile.jpg](https://github.com/tinar9678/tinar9678.github.io/blob/master/pictures/profile.jpg) hit the "Raw" button.

**Comment by EliasOPrado** [comment]
@sthodup1 it could help me if you share the real solution here.

**Comment by johnfrail** [comment]
> @sthodup1 it could help me if you share the real solution here.

Just use netlify, it is very simple.
